version: "3"

networks:
  masters:
    external: true

services:
  grpc-go:
    image: grpc-go
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "9082:8082"
      - "9080:8080"
    networks:
      - masters